### ISSUE TITLE
Unable to contribute?

### ISSUE THREAD

**Issue by saddiqs1** [sruusk/esea-scraper#189]
Hi, I want to contribute to this repo and have implemented a method which retrieves a user's esea profile given a steamid. Would it be possible to open this repo up to allow people to contribute, or do you not intend for this to be expanded upon?

**Comment by sruusk** [comment]
Hi. There should be no restrictions on creating pull requests. I couldn't find any fork on your account. Have you tried forking this repository, committing your changes and then attempting to open a pull request?

**Comment by saddiqs1** [comment]
Apologies I thought I could just make a branch on the repo directly - first time contributing to a repo :D

Here's the link https://github.com/sruusk/esea-scraper/pull/190
