### ISSUE TITLE
Out of curiosity, how do you run this in a deployed web app?

### ISSUE THREAD

**Issue by saddiqs1** [sruusk/esea-scraper#191]
I'm currently trying to run this within a vercel deployment, but am struggling to get ulixee working. Any ideas/suggestions on how to get it to work?

**Comment by sruusk** [comment]
There's a couple things that might cause you problems.  
1. You need x86 architecture CPU to run the browser and you may not be able to install it on a managed deployment.  
2. You can't run it from an datacenter IP, as cloudflare will block you based on the IP address.  
3. You may need to run an install script to setup the browser.  

As for what I'm running:
- Debian 11 VPS
- [Ulixee Cloud](https://ulixee.org/docs/cloud) instance running inside a namespaced OpenVPN tunnel that the scraper connects to.

**Comment by saddiqs1** [comment]
For my needs I think this isn't suitable, so i've decided to go with a completely different route altogether now. Thanks for the response though!
